---
ConnectionStrings:
  Redis.off: localhost,abortConnect=false
  Elasticsearch.off: http://localhost:9200/
  Ldap.off: ''

# Base url for the ui used to build links in emails and other places.
BaseURL: 'http://localhost:9001/#!'

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning