---
ConnectionStrings:
  RedisConnectionString.off: localhost,abortConnect=false
  ElasticsearchConnectionString.off: http://localhost:9200/

Logging:
  IncludeScopes: false
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information