---
ConnectionStrings:
  RedisConnectionString.off: localhost,abortConnect=false
  ElasticsearchConnectionString.off: http://localhost:9200/
  LdapConnectionString.off: ''

  # Base url for the ui used to build links in emails and other places.
BaseURL: 'https://dev.exceptionless.io'
# Controls whether SSL is required. Only enable this if you have SSL configured.
EnableSSL: true

# Runs the jobs in the current website process
RunJobsInProcess: false