---
ConnectionStrings:
  elasticsearch.off: server=http://localhost:9200
  cache.off: provider=redis;localhost,abortConnect=false
  messagebus.off: provider=redis;localhost,abortConnect=false
  metric.off: provider=statsd;server=10.0.0.5;
  queue.off: provider=redis;localhost,abortConnect=false
  storage.off: ''
  email.off: 'smtps://user:password@domain.com:587'
  ldap.off: ''

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://be.exceptionless.io

# Controls whether users can signup.
EnableAccountCreation: true

# Email
# SmtpFrom:Exceptionless <noreply@exceptionless.io>

# Exceptionless Client Settings
ExceptionlessServerUrl: https://collector.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823

FacebookAppId: 395178683904310
GitHubAppId: 7ef1dd5bfbc4ccf7f5ef
GoogleAppId: 809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com
MicrosoftAppId: 000000004C137E8B
SlackAppId: 34500115540.177239122322
StripePublishableApiKey: pk_live_QTiVo5Fqv7uNScqIpd1Ns9gX