---
Serilog:
  Using:
  - Serilog.Sinks.Console
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Information
      System: Information
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning
  WriteTo:
  - Name: Console
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId