---
ConnectionStrings:
  Elasticsearch.off: server=http://localhost:9200
  Cache.off: provider=redis;server="localhost,abortConnect=false"
  MessageBus.off: provider=redis;server="localhost,abortConnect=false"
  Queue.off: provider=redis;server="localhost,abortConnect=false"
  Storage: provider=folder;path=.\storage
  LDAP.off: ''

# Base url for the ui used to build links in emails and other places.
BaseURL: 'http://localhost:9001/#!'

# Wether or not to run the jobs in process. Requires Redis to be configured when running jobs out of process.
RunJobsInProcess: true

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      System: Warning
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning