version: '3.4'

services:
  # job:
  #   depends_on:
  #     - elasticsearch
  #   image: job
  #   build:
  #     context: .
  #     target: job
  #   networks:
  #     - exceptionless

  web:
    depends_on:
      - elasticsearch
    image: web
    build:
      context: .
      target: web
    environment:
      ConnectionStrings_ElasticSearchConnectionString: http://elasticsearch:9200
    ports:
      - 5000:80
    networks:
      - exceptionless

  elasticsearch:
    image: slideroom/elasticsearch:98
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      xpack.security.enabled: 'false'
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - exceptionless

  kibana:
    depends_on:
      - elasticsearch
    image: slideroom/kibana:116
    ports:
      - 5601:5601
    networks:
      - exceptionless

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - exceptionless
 
volumes:
  esdata:
    driver: local

networks:
  exceptionless:
    driver: bridge
