receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/elastic:
    endpoint: apm:8200
    tls:
        insecure: true
  logging:
    loglevel: debug
    sampling_initial: 500
    sampling_thereafter: 1

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/elastic, logging ]
    metrics:
      receivers: [ otlp ]
      exporters: [ otlp/elastic, logging ]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp/elastic, logging ]