apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "exceptionless.fullname" . }}-config
data:
    AppMode: Development
{{- if (.Values.elasticsearch.connectionString) }}
    ConnectionStrings__Elasticsearch: {{.Values.elasticsearch.connectionString}}
{{- else }}
    ConnectionStrings__Elasticsearch: http://{{ template "exceptionless.fullname" . }}-elasticsearch:9200
{{- end }}
{{- if (.Values.redis.connectionString) }}
    ConnectionStrings__Redis: {{.Values.redis.connectionString}}
{{- else }}
    ConnectionStrings__Redis: {{ template "exceptionless.fullname" . }}-redis,abortConnect=false
{{- end }}
{{- if (.Values.storage.azureConnectionString) }}
    ConnectionStrings__AzureStorage: {{.Values.storage.azureConnectionString}}
{{- else }}
    StorageFolder: /app/storage
{{- end }}
    BaseUrl: http://ex-api.localtest.me:5000
