appMode: Staging
appScope: dev
api:
  replicaCount: 0
  image:
    repository: exceptionless/api-ci
  defaultDomain: dev-api.exceptionless.io
  domains:
    - dev-api.exceptionless.io
app:
  replicaCount: 0
  image:
    repository: exceptionless/ui-ci
  defaultDomain: dev-app.exceptionless.io
  domains:
    - dev-app.exceptionless.io
collector:
  replicaCount: 0
  defaultDomain: dev-collector.exceptionless.io
  domains:
    - dev-collector.exceptionless.io
jobs:
  image:
    repository: exceptionless/job-ci
  eventNotifications:
    replicaCount: 0
  eventPosts:
    replicaCount: 0
  stackEventCount:
    replicaCount: 0
  eventUserDescriptions:
    replicaCount: 0
  mailMessage:
    replicaCount: 0
  webhooks:
    replicaCount: 0
  workitem:
    replicaCount: 0
  closeInactiveSessions:
    replicaCount: 0
  dailySummary:
    replicaCount: 0

config:
  EX_EnableSnapshotJobs: "false"