apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ex-prod-monitor
  namespace: ex-prod
spec:
  version: 8.2.2
  nodeSets:
  - name: default
    count: 1
    config:
      # if not setting max_map_count in an init container, then use this setting
      #node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          resources:
            requests:
              memory: 8Gi
              cpu: 2
            limits:
              memory: 8Gi
        # related to "node.store.allow_mmap: false" setting above
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: managed-premium

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: ex-prod-monitor
  namespace: ex-prod
spec:
  version: 8.2.2
  count: 1
  elasticsearchRef:
    name: ex-prod-monitor
  config:
    xpack.fleet.packages:
    - name: apm
      version: latest

---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: ex-prod-monitor
spec:
  version: 8.2.2
  count: 1
  elasticsearchRef:
    name: ex-prod-monitor
  kibanaRef:
    name: ex-prod-monitor