appMode: Production
appScope: prod
api:
  replicaCount: 3
  defaultDomain: api.exceptionless.io
  domains:
    - api.exceptionless.io
    - api.exceptionless.com
app:
  replicaCount: 2
  defaultDomain: be.exceptionless.io
  domains:
    - be.exceptionless.io
    - app.exceptionless.io
    - app.exceptionless.com
collector:
  replicaCount: 5
  defaultDomain: collector.exceptionless.io
  domains:
    - collector.exceptionless.io
    - collector.exceptionless.com
    - config.exceptionless.io
    - heartbeat.exceptionless.io
jobs:
  eventNotifications:
    replicaCount: 2
  eventPosts:
    replicaCount: 10
  eventUserDescriptions:
    replicaCount: 2
  mailMessage:
    replicaCount: 2
  webhooks:
    replicaCount: 2
  workitem:
    replicaCount: 4

config:
  EX_EnableSnapshotJobs: "true"
  EX_SmtpFrom: "Exceptionless <noreply@exceptionless.io>"
  EX_TestEmailAddress: "test@exceptionless.io"
  EX_EnableArchive: "false"
  EX_Apm__Endpoint: http://ex-prod-monitor-apm-http:8200
  EX_Apm__EnableLogs: "true"
  EX_Apm__EnableMetrics: "true"
  EX_Apm__EnableTracing: "true"
  EX_Apm__FullDetails: "true"
  EX_Apm__Insecure: "false"
