api:
  replicaCount: 1
  image:
    repository: exceptionless/api-ci
    tag: latest
    pullPolicy: IfNotPresent

app:
  replicaCount: 1
  image:
    repository: exceptionless/app-ci
    tag: latest
    pullPolicy: IfNotPresent

jobs:
  replicaCount: 1
  image:
    repository: exceptionless/job-ci
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: ClusterIP # LoadBalancer

elasticsearch:
  image:
    repository: slideroom/elasticsearch
    tag: 98
    pullPolicy: IfNotPresent
