api:
  replicaCount: 1
  image:
    repository: exceptionless/api-ci
    tag: latest
    pullPolicy: IfNotPresent

app:
  replicaCount: 1
  image:
    repository: exceptionless/ui-ci
    tag: latest
    pullPolicy: IfNotPresent

jobs:
  replicaCount: 1
  image:
    repository: exceptionless/job-ci
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: LoadBalancer # ClusterIP

elasticsearch:
  connectionString: 
  image:
    repository: slideroom/elasticsearch
    tag: 98
    pullPolicy: IfNotPresent

redis:
  connectionString: 
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
