---
ConnectionStrings:
  RedisConnectionString.off: 'localhost,abortConnect=false'
  ElasticsearchConnectionString.off: http://localhost:9200/

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Information
      System: Information
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning