---
ConnectionStrings:
  RedisConnectionString.off: localhost,abortConnect=false
  ElasticsearchConnectionString.off: http://localhost:9200/

# Base url for the ui used to build links in emails and other places.
BaseURL: 'http://localhost:9001/#!'

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Information
      System: Information
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning