apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "exceptionless.fullname" . }}-app
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-app
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "exceptionless.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ template "exceptionless.name" . }}
        component: {{ template "exceptionless.fullname" . }}-app
        chart: {{ template "exceptionless.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ template "exceptionless.name" . }}-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ template "exceptionless.fullname" . }}-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "exceptionless.fullname" . }}-app
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-app
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: {{ template "exceptionless.fullname" . }}-app
