---
DisableIndexConfiguration: true

Serilog:
  Using:
  - Serilog.Sinks.Console
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      System: Warning
      Foundatio.Utility.ScheduledTimer: Warning
      Foundatio.Metrics: Warning
      Microsoft.AspNetCore.Hosting.Diagnostics: Warning
      Exceptionless.Web.Security.ApiKeyAuthenticationHandler: Warning
      Exceptionless: Information
      Foundatio: Information
  WriteTo:
  - Name: Console
    Args: 
      theme: "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Literate, Serilog.Sinks.Console"
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithThreadId

Apm:
  ServiceName: exceptionless
  EnableLogs: false
  EnableTracing: false
  SampleRate: 1.0
  FullDetails: true
  Debug: false