---
ConnectionStrings:
#  Redis: server="localhost,abortConnect=false"
#  Elasticsearch: server=https://elastic:elastic@localhost:9200
#  Cache: provider=redis;
#  MessageBus: provider=redis;
#  Queue: provider=redis;
  Storage: provider=folder;path=..\Exceptionless.Web\storage
  Email: smtp://localhost:1025

# Base url for the ui used to build links in emails and other places.
BaseURL: 'http://localhost:9001/#!'

Serilog:
  MinimumLevel:
    Default: Debug

Apm:
  #Endpoint: http://host.docker.internal:8200
  Insecure: true
  EnableLogs: false
  EnableTracing: false
  EnableMetrics: true
  FullDetails: true
  Debug: false
  Console: false
